# config.yaml

#################
# CONFIGURATION #
#################

# Repo author name
repo_author: AUTHOR_NAME

# ROS2 workspace to mount at run-time
project_repo: PROJECT_REPO

# Extra volumes (absolute path) to mount at run-time
volumes: [
  # "/path/to/dir",
]

# ROS2 distro selected for build-time
middleware: ros2
ros2_distro: jazzy
target_platorm: x86_64

# Image/Container environment variables
container_env:
  container_usr: docker
  container_psw: password
  container_uid: 1000
  container_gid: 1000

# Container command at run-time
container_run_cmd: /bin/bash


#############
# CONSTANTS #
#############

docker_base_images:
  x86_full_image: "osrf/ros:ROS2_DISTRO-desktop-full"
  arm_base_image: "arm64v8/ros:ROS2_DISTRO-ros-base"
  microros_base_image: "microros/base:ROS2_DISTRO"

docker_file_image_container:
  dockerfile: Dockerfile_MIDDLEWARE
  docker_image: REPO_AUTHOR/PROJECT_REPO-ROS2_DISTRO-image
  docker_container: PROJECT_REPO-TAG-container

supported:
  architectures: [develop, x86_64, deploy, arm, aarch64, freertos, nuttx, zephyr]
  middlewares: [ros2, micro-ros]
  ros2_distros: [humble, jazzy, rolling]
